const coachController = require('../controllers/coach.controller')
const assignmentController = require('../controllers/assignment.controller')
const learningController = require('../controllers/learning.controller')
const { auth } = require('../middleware/auth')
const { ROLES } = require('../config/constants')

const coachOnly = auth([ROLES.COACH])

const register = (route) => {
  route('GET', '/api/coach/stats', [coachOnly, coachController.stats])
  route('GET', '/api/coach/students', [coachOnly, coachController.students])
  route('GET', '/api/coach/earnings', [coachOnly, coachController.earnings])
  route('GET', '/api/coach/lessons', [coachOnly, learningController.listCoachLessons])
  route('POST', '/api/coach/lessons', [coachOnly, learningController.createCoachLesson])
  route('PUT', '/api/coach/lessons/:id', [coachOnly, learningController.updateCoachLesson])
  route('PATCH', '/api/coach/lessons/:id', [coachOnly, learningController.updateCoachLesson])
  route('DELETE', '/api/coach/lessons/:id', [coachOnly, learningController.deleteCoachLesson])
  route('GET', '/api/coach/topics', [coachOnly, learningController.listCoachTopics])
  route('POST', '/api/coach/topics', [coachOnly, learningController.createCoachTopic])
  route('PUT', '/api/coach/topics/:id', [coachOnly, learningController.updateCoachTopic])
  route('PATCH', '/api/coach/topics/:id', [coachOnly, learningController.updateCoachTopic])
  route('DELETE', '/api/coach/topics/:id', [coachOnly, learningController.deleteCoachTopic])
  route('GET', '/api/coach/quizzes', [coachOnly, learningController.listCoachQuizzes])
  route('GET', '/api/coach/quizzes/:id', [coachOnly, learningController.getCoachQuiz])
  route('POST', '/api/coach/quizzes', [coachOnly, learningController.createCoachQuiz])
  route('PUT', '/api/coach/quizzes/:id', [coachOnly, learningController.updateCoachQuiz])
  route('PATCH', '/api/coach/quizzes/:id', [coachOnly, learningController.updateCoachQuiz])
  route('DELETE', '/api/coach/quizzes/:id', [coachOnly, learningController.deleteCoachQuiz])
  route('GET', '/api/coach/assignments', [coachOnly, assignmentController.list])
  route('PATCH', '/api/coach/assignments/submissions/:id/review', [coachOnly, assignmentController.reviewSubmission])
  route('POST', '/api/coach/assignments', [coachOnly, assignmentController.create])
  route('PUT', '/api/coach/assignments/:id', [coachOnly, assignmentController.update])
  route('PATCH', '/api/coach/assignments/:id', [coachOnly, assignmentController.update])
  route('DELETE', '/api/coach/assignments/:id', [coachOnly, assignmentController.remove])
  route('GET', '/api/coach/materials', [coachOnly, learningController.listCoachMaterials])
  route('POST', '/api/coach/materials', [coachOnly, learningController.createCoachMaterial])
  route('DELETE', '/api/coach/materials/:id', [coachOnly, learningController.deleteCoachMaterial])
  route('GET', '/api/coach/pricing-plans', [coachOnly, learningController.listPricingPlans])
  route('POST', '/api/coach/pricing-plans', [coachOnly, learningController.createPricingPlan])
  route('PUT', '/api/coach/pricing-plans/:id', [coachOnly, learningController.updatePricingPlan])
  route('PATCH', '/api/coach/pricing-plans/:id', [coachOnly, learningController.updatePricingPlan])
  route('DELETE', '/api/coach/pricing-plans/:id', [coachOnly, learningController.deletePricingPlan])
}

module.exports = { register }
